#!/bin/bash
#$ -l h_rt=200:00:00
#$ -l h_vmem=11G
#$ -pe smp 8
#$ -l gpu=1
#$ -l gpu_type=ampere
#$ -wd /data/home/eey362/code/coco-captions-extended/
#$ -j y
#$ -m ea
#$ -o logs/
#$ -l cluster=andrena
#$ -l rocky


# Load modules
module purge

module load python/3.11.7-gcc-12.2.0
module load cuda/12.6.2-gcc-12.2.0

source .venv/bin/activate

python3 main.py --karpathy "/data/EECS-YuanLab/COCO/dataset_coco.json" \
                --coco_img_root "/data/PublicDataSets/Coco-2014/" \
                --output "/data/EECS-YuanLab/COCO/dataset_coco_ext_${LENGTH}.json" \
                --target_seq_len ${LENGTH} \
		--batch_size 8 \
                --split "test"

